// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJpNt75EPmKbcxr5OUjnA50n8MlQ-Znxg',
    appId: '1:302045304360:web:72add38f743ed42826471d',
    messagingSenderId: '302045304360',
    projectId: 'flutter-car-rental-app-d02df',
    authDomain: 'flutter-car-rental-app-d02df.firebaseapp.com',
    storageBucket: 'flutter-car-rental-app-d02df.firebasestorage.app',
    measurementId: 'G-WS2B8V0CN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Cyiz4_9eYy9weuluu-JDHJ7hgTGH294',
    appId: '1:302045304360:android:be9ab96bf3994f0226471d',
    messagingSenderId: '302045304360',
    projectId: 'flutter-car-rental-app-d02df',
    storageBucket: 'flutter-car-rental-app-d02df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBktydOOhaYb9-ZxiUACTwj-TJLjZvrjDQ',
    appId: '1:302045304360:ios:e9a46fb0e3d06aff26471d',
    messagingSenderId: '302045304360',
    projectId: 'flutter-car-rental-app-d02df',
    storageBucket: 'flutter-car-rental-app-d02df.firebasestorage.app',
    iosBundleId: 'com.example.buildCarRentalAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBktydOOhaYb9-ZxiUACTwj-TJLjZvrjDQ',
    appId: '1:302045304360:ios:e9a46fb0e3d06aff26471d',
    messagingSenderId: '302045304360',
    projectId: 'flutter-car-rental-app-d02df',
    storageBucket: 'flutter-car-rental-app-d02df.firebasestorage.app',
    iosBundleId: 'com.example.buildCarRentalAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJpNt75EPmKbcxr5OUjnA50n8MlQ-Znxg',
    appId: '1:302045304360:web:a5f14ca5d6ca7f3326471d',
    messagingSenderId: '302045304360',
    projectId: 'flutter-car-rental-app-d02df',
    authDomain: 'flutter-car-rental-app-d02df.firebaseapp.com',
    storageBucket: 'flutter-car-rental-app-d02df.firebasestorage.app',
    measurementId: 'G-ZGQ2R3DPSN',
  );
}
